name: UpdateHosts

on:
  schedule:
    - cron: "0 */2 * * *"  # 每两小时运行一次（UTC 时间）
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Update hosts
        run: npm run start

      - name: Commit
        id: commit
        run: |
          git config --global user.email "hostsBot@fake.com"
          git config --global user.name "hostsBot"
          git add .
          git commit -m "Update hosts"
        continue-on-error: true

      - name: Check on failures
        if: steps.commit.outputs.status == 'failure'
        run: exit 1

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     
      - name: Sync to Gitee
        run: |
          git remote add gitee https://${{ secrets.GITEE_USER }}:${{ secrets.GITEE_TOKEN }}@gitee.com/${{ secrets.GITEE_REPO_PATH }}.git
          git push --force gitee HEAD:main
        env:
          GIT_AUTHOR_NAME: "hostsBot"
          GIT_AUTHOR_EMAIL: "hostsBot@fake.com"
          GIT_COMMITTER_NAME: "hostsBot"
          GIT_COMMITTER_EMAIL: "hostsBot@fake.com"
